_wandb:
    value:
        cli_version: 0.24.2
        e:
            xj1zcfy771gtwknnnzduo9varol48jsy:
                apple:
                    ecpuCores: 4
                    gpuCores: 8
                    memoryGb: 16
                    name: Apple M2
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                codePath: ml/train_decoder.py
                codePathLocal: train_decoder.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "242379546624"
                email: j.r.h.wood98@gmail.com
                executable: /Library/Developer/CommandLineTools/usr/bin/python3
                git:
                    commit: 8a87b2b91f7baa00ac8136ac9ad76477617bfee6
                    remote: git@github.com:woodRock/depth-learning.git
                host: Mac.staff.vuw.ac.nz
                memory:
                    total: "17179869184"
                os: macOS-15.5-arm64-arm-64bit
                program: /Users/woodj/Desktop/depth-learning/ml/train_decoder.py
                python: CPython 3.9.6
                root: /Users/woodj/Desktop/depth-learning/ml
                startedAt: "2026-03-18T02:19:49.235057Z"
                writerId: xj1zcfy771gtwknnnzduo9varol48jsy
        m: []
        python_version: 3.9.6
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "4": 3.9.6
            "5": 0.24.2
            "12": 0.24.2
            "13": darwin-arm64
